### ISSUE TITLE
Consider using CSV as the data source

### ISSUE THREAD

**Issue by benbalter** [GSA/Very-Simple-API#7]
Now that Jekyll 2.4.0 can read CSV interchangeably with YML in the data folder, may be easier to then, e.g., edit in Excel, export. paste, and have an API, rather than learning a new format.

**Comment by gbinal** [comment]
I'm def. very interested in this.  How would I do it differently [than I am here](https://github.com/GSA/Very-Simple-API-2)?  

Right now, https://gsa.github.io/Very-Simple-API-2/dogs.json isn't generating json for me.

**Comment by benbalter** [comment]
> How would I do it differently than I am here?

`_data`: http://jekyllrb.com/docs/datafiles/

**Comment by gbinal** [comment]
Dang!  Sorry about that.  Fixed and rocking.  

![screen shot 2014-10-23 at 3 37 38 pm](https://cloud.githubusercontent.com/assets/633088/4760013/10415680-5aec-11e4-95f9-4ea666c06116.png)
